name: CI

jobs:
build-kernel:
 runs-on: ubuntu-22.04
 steps:
   - name: Checkout with submodules
     uses: actions/checkout@v4
     with:
       path: msm-4.4  # 强制将代码检出到子目录
       submodules: recursive

   - name: Debug directory structure
     run: |
       pwd
       ls -la msm-4.4
       ls -la msm-4.4/arch/arm64/configs/

   - name: Build with working directory
     uses: dabao1955/kernel_build_action@main
     with:
       kernel-url: ""  # 禁用自动拉取代码
       config: arch/arm64/configs/msmcortex-NX563J-perf_defconfig
       arch: arm64
       android-version: 12
       aosp-clang-version: r383902
       # 新增关键参数
       source-dir: ${{ github.workspace }}/msm-4.4
       make-flags: O=out
     working-directory: msm-4.4  # 强制切换工作目录
