name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ztemt/NX563J_P_kernel
          kernel-branch: master
          # 显式指定配置文件完整相对路径
          config: arch/arm64/configs/msmcortex-NX563J-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          # 强制指定内核源路径
          source-dir: msm-4.4
