name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: dabao1955/kernel_build_action@main
     with:
       path: msm-4.4  # 强制将代码检出到子目录
       submodules: recursive

   - name: Debug directory structure
     run: |
       pwd
       ls -la msm-4.4
       ls -la msm-4.4/arch/arm64/configs/

   - name: Build with working directory
     uses: dabao1955/kernel_build_action@main
     with:
       kernel-url: https://github.com/ztemt/NX563J_P_kernel
       config: arch/arm64/configs/msmcortex-NX563J-perf_defconfig
       arch: arm64
       android-version: 12
       aosp-clang-version: r383902
       make-flags: O=out
